// Code generated by muxt. DO NOT EDIT.
// muxt version: v0.17.3
//
// MIT License
//
// Copyright (c) 2025 Christopher Hunter
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
package hypertext

import (
	"bytes"
	"cmp"
	"context"
	"fmt"
	"log/slog"
	"net/http"
	"path"
	"strconv"

	"github.com/typelate/example-sortable/internal/database"
)

type RoutesReceiver interface {
	Lists(ctx context.Context) []database.List
	GetList(ctx context.Context, id int32) ListData
	UpdateList(ctx context.Context, listID int32, form UpdateListForm) ListData
}

func Routes(mux *http.ServeMux, receiver RoutesReceiver) {
	mux.HandleFunc("GET /", func(response http.ResponseWriter, request *http.Request) {
		ctx := request.Context()
		result := receiver.Lists(ctx)
		td := newTemplateData(receiver, response, request, result, true, nil)
		buf := bytes.NewBuffer(nil)
		if err := templates.ExecuteTemplate(buf, "GET / Lists(ctx)", td); err != nil {
			slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
			http.Error(response, "failed to render page", http.StatusInternalServerError)
			return
		}
		statusCode := cmp.Or(td.statusCode, http.StatusOK)
		if td.redirectURL != "" {
			http.Redirect(response, request, td.redirectURL, statusCode)
			return
		}
		if contentType := response.Header().Get("content-type"); contentType == "" {
			response.Header().Set("content-type", "text/html; charset=utf-8")
		}
		response.Header().Set("content-length", strconv.Itoa(buf.Len()))
		response.WriteHeader(statusCode)
		_, _ = buf.WriteTo(response)
	})
	mux.HandleFunc("GET /list/{id}", func(response http.ResponseWriter, request *http.Request) {
		ctx := request.Context()
		idParsed, err := strconv.ParseInt(request.PathValue("id"), 10, 32)
		if err != nil {
			var zv ListData
			rd := newTemplateData(receiver, response, request, zv, false, err)
			buf := bytes.NewBuffer(nil)
			if err := templates.ExecuteTemplate(buf, "GET /list/{id} GetList(ctx, id)", rd); err != nil {
				slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
				http.Error(response, "failed to render page", http.StatusInternalServerError)
				return
			}
			sc := cmp.Or(rd.statusCode, http.StatusBadRequest)
			if rd.redirectURL != "" {
				http.Redirect(response, request, rd.redirectURL, sc)
				return
			}
			if contentType := response.Header().Get("content-type"); contentType == "" {
				response.Header().Set("content-type", "text/html; charset=utf-8")
			}
			response.Header().Set("content-length", strconv.Itoa(buf.Len()))
			response.WriteHeader(sc)
			_, _ = buf.WriteTo(response)
			return
		}
		id := int32(idParsed)
		result := receiver.GetList(ctx, id)
		td := newTemplateData(receiver, response, request, result, true, nil)
		buf := bytes.NewBuffer(nil)
		if err := templates.ExecuteTemplate(buf, "GET /list/{id} GetList(ctx, id)", td); err != nil {
			slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
			http.Error(response, "failed to render page", http.StatusInternalServerError)
			return
		}
		statusCode := cmp.Or(td.statusCode, http.StatusOK)
		if td.redirectURL != "" {
			http.Redirect(response, request, td.redirectURL, statusCode)
			return
		}
		if contentType := response.Header().Get("content-type"); contentType == "" {
			response.Header().Set("content-type", "text/html; charset=utf-8")
		}
		response.Header().Set("content-length", strconv.Itoa(buf.Len()))
		response.WriteHeader(statusCode)
		_, _ = buf.WriteTo(response)
	})
	mux.HandleFunc("POST /list/{id}", func(response http.ResponseWriter, request *http.Request) {
		ctx := request.Context()
		idParsed, err := strconv.ParseInt(request.PathValue("id"), 10, 32)
		if err != nil {
			var zv ListData
			rd := newTemplateData(receiver, response, request, zv, false, err)
			buf := bytes.NewBuffer(nil)
			if err := templates.ExecuteTemplate(buf, "POST /list/{id} UpdateList(ctx, id, form)", rd); err != nil {
				slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
				http.Error(response, "failed to render page", http.StatusInternalServerError)
				return
			}
			sc := cmp.Or(rd.statusCode, http.StatusBadRequest)
			if rd.redirectURL != "" {
				http.Redirect(response, request, rd.redirectURL, sc)
				return
			}
			if contentType := response.Header().Get("content-type"); contentType == "" {
				response.Header().Set("content-type", "text/html; charset=utf-8")
			}
			response.Header().Set("content-length", strconv.Itoa(buf.Len()))
			response.WriteHeader(sc)
			_, _ = buf.WriteTo(response)
			return
		}
		id := int32(idParsed)
		request.ParseForm()
		var form UpdateListForm
		for _, val := range request.Form["task-id"] {
			value, err := strconv.ParseInt(val, 10, 32)
			if err != nil {
				var zv ListData
				rd := newTemplateData(receiver, response, request, zv, false, err)
				buf := bytes.NewBuffer(nil)
				if err := templates.ExecuteTemplate(buf, "POST /list/{id} UpdateList(ctx, id, form)", rd); err != nil {
					slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
					http.Error(response, "failed to render page", http.StatusInternalServerError)
					return
				}
				sc := cmp.Or(rd.statusCode, http.StatusBadRequest)
				if rd.redirectURL != "" {
					http.Redirect(response, request, rd.redirectURL, sc)
					return
				}
				if contentType := response.Header().Get("content-type"); contentType == "" {
					response.Header().Set("content-type", "text/html; charset=utf-8")
				}
				response.Header().Set("content-length", strconv.Itoa(buf.Len()))
				response.WriteHeader(sc)
				_, _ = buf.WriteTo(response)
				return
			}
			form.TaskIDs = append(form.TaskIDs, int32(value))
		}
		result := receiver.UpdateList(ctx, id, form)
		td := newTemplateData(receiver, response, request, result, true, nil)
		buf := bytes.NewBuffer(nil)
		if err := templates.ExecuteTemplate(buf, "POST /list/{id} UpdateList(ctx, id, form)", td); err != nil {
			slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
			http.Error(response, "failed to render page", http.StatusInternalServerError)
			return
		}
		statusCode := cmp.Or(td.statusCode, http.StatusOK)
		if td.redirectURL != "" {
			http.Redirect(response, request, td.redirectURL, statusCode)
			return
		}
		if contentType := response.Header().Get("content-type"); contentType == "" {
			response.Header().Set("content-type", "text/html; charset=utf-8")
		}
		response.Header().Set("content-length", strconv.Itoa(buf.Len()))
		response.WriteHeader(statusCode)
		_, _ = buf.WriteTo(response)
	})
}

type TemplateData[T any] struct {
	receiver    RoutesReceiver
	response    http.ResponseWriter
	request     *http.Request
	result      T
	statusCode  int
	okay        bool
	err         error
	redirectURL string
}

func newTemplateData[T any](receiver RoutesReceiver, response http.ResponseWriter, request *http.Request, result T, okay bool, err error) *TemplateData[T] {
	return &TemplateData[T]{receiver: receiver, response: response, request: request, result: result, okay: okay, err: err, redirectURL: ""}
}

func (data *TemplateData[T]) MuxtVersion() string {
	const muxtVersion = "v0.17.3"
	return muxtVersion
}

func (data *TemplateData[T]) Path() TemplateRoutePaths {
	return TemplateRoutePaths{}
}

func (data *TemplateData[T]) Result() T {
	return data.result
}

func (data *TemplateData[T]) Request() *http.Request {
	return data.request
}

func (data *TemplateData[T]) StatusCode(statusCode int) *TemplateData[T] {
	data.statusCode = statusCode
	return data
}

func (data *TemplateData[T]) Header(key, value string) *TemplateData[T] {
	data.response.Header().Set(key, value)
	return data
}

func (data *TemplateData[T]) Ok() bool {
	return data.okay
}

func (data *TemplateData[T]) Err() error {
	return data.err
}

func (data *TemplateData[T]) Receiver() RoutesReceiver {
	return data.receiver
}

func (data *TemplateData[T]) Redirect(url string, code int) (*TemplateData[T], error) {
	if code < 300 || code >= 400 {
		return data, fmt.Errorf("invalid status code %d for redirect", code)
	}
	data.redirectURL = url
	return data.StatusCode(code), nil
}

type TemplateRoutePaths struct {
}

func (TemplateRoutePaths) Lists() string {
	return "/"
}

func (TemplateRoutePaths) GetList(id int32) string {
	return "/" + path.Join("list", strconv.FormatInt(int64(id), 10))
}

func (TemplateRoutePaths) UpdateList(id int32) string {
	return "/" + path.Join("list", strconv.FormatInt(int64(id), 10))
}
